//! MVCC (multi-version concurrency control) subsystem.
//!
//! This module hosts the WiredTiger-style in-memory version chain,
//! Hybrid Logical Clock timestamp oracle, read-view registry, and
//! reconciliation / deferred-free plumbing.

pub mod deferred_free;
pub mod metrics;
pub mod read_view;
pub mod timestamp;
pub mod transaction;
pub mod version;

#[allow(unused_imports)]
pub use deferred_free::DeferredFreeQueue;
#[allow(unused_imports)]
pub use metrics::{
    active_read_views_snapshot,
    // Phase 1 §10.10 counters (US-012)
    catalog_header_sync_count_snapshot,
    chain_migration_entries_moved_snapshot,
    commit_seq_wait_ns_snapshot,
    crud_commits_root_changing_snapshot,
    crud_commits_root_neutral_snapshot,
    deferred_free_queue_depth_snapshot,
    delta_bearing_frames_count_snapshot,
    delta_bearing_frames_ratio_snapshot,
    emergency_checkpoint_triggers_snapshot,
    force_expire_spin_stalls_snapshot,
    history_store_bytes_snapshot,
    history_store_gc_passes_snapshot,
    hlc_advance_events_snapshot,
    journal_chain_commit_frames_snapshot,
    journal_commits_snapshot,
    lane_wait_ns_snapshot,
    // Phase 2 §7 / US-024 — logical-frame counters / gauges
    logical_txn_append_bytes_snapshot,
    logical_txn_append_duration_ms_p50_snapshot,
    logical_txn_append_duration_ms_p95_snapshot,
    logical_txn_append_duration_ms_p99_snapshot,
    logical_txn_pass1_orphan_logical_dropped_snapshot,
    logical_txn_pass1_pre_boundary_dropped_snapshot,
    logical_txn_pass1_unmatched_chain_commit_snapshot,
    logical_txn_pass2_resolved_ops_snapshot,
    logical_txn_pass2_unresolved_ops_snapshot,
    logical_txn_recovery_discarded_frames_snapshot,
    logical_txn_torn_frames_snapshot,
    oldest_required_ts_lag_ms_snapshot,
    overflow_pages_freed_snapshot,
    overflow_pages_in_use_snapshot,
    overflow_refcount_cas_retries_snapshot,
    parsed_logical_frames_len_snapshot,
    published_catalog_rebuild_count_snapshot,
    published_snapshot_rebuilds_snapshot,
    read_epoch_publish_count_snapshot,
    read_views_force_expired_snapshot,
    recompute_logical_txn_append_percentiles,
    reconcile_duration_ms_p99_snapshot,
    reconcile_entries_dropped_snapshot,
    record_catalog_header_sync,
    record_chain_migration_entries_moved,
    record_commit_seq_wait_ns,
    record_crud_commit_root_changing,
    record_crud_commit_root_neutral,
    record_delta_bearing_frame,
    record_emergency_checkpoint_trigger,
    record_force_expire_spin_stall,
    record_history_store_gc_pass,
    record_hlc_advance,
    record_journal_chain_commit_frame,
    record_journal_commit,
    record_lane_wait_ns,
    record_logical_txn_append_bytes,
    record_logical_txn_append_duration_ms,
    record_logical_txn_pass1_orphan_logical_dropped,
    record_logical_txn_pass1_pre_boundary_dropped,
    record_logical_txn_pass1_unmatched_chain_commit,
    record_logical_txn_pass2_resolved_op,
    record_logical_txn_pass2_unresolved_op,
    record_logical_txn_recovery_discarded_frame,
    record_logical_txn_torn_frame,
    record_overflow_page_freed,
    record_overflow_refcount_cas_retry,
    record_published_catalog_rebuild,
    record_published_snapshot_rebuild,
    record_read_epoch_publish,
    record_read_view_force_expired,
    record_reconcile_entries_dropped,
    record_recovery_chain_commit_frame,
    record_recovery_legacy_page_frame,
    record_root_neutral_commit,
    record_secondary_index_tombstone_hit,
    recovery_chain_commit_frames_snapshot,
    recovery_legacy_page_frames_snapshot,
    reset_active_read_views,
    reset_catalog_header_sync_count,
    reset_chain_migration_entries_moved,
    reset_commit_seq_wait_ns,
    reset_crud_commits_root_changing,
    reset_crud_commits_root_neutral,
    reset_deferred_free_queue_depth,
    reset_delta_bearing_frames_count,
    reset_delta_bearing_frames_ratio,
    reset_emergency_checkpoint_triggers,
    reset_force_expire_spin_stalls,
    reset_history_store_bytes,
    reset_history_store_gc_passes,
    reset_hlc_advance_events,
    reset_journal_chain_commit_frames,
    reset_journal_commits,
    reset_lane_wait_ns,
    reset_logical_txn_append_bytes,
    reset_logical_txn_append_durations,
    reset_logical_txn_pass1_orphan_logical_dropped,
    reset_logical_txn_pass1_pre_boundary_dropped,
    reset_logical_txn_pass1_unmatched_chain_commit,
    reset_logical_txn_pass2_resolved_ops,
    reset_logical_txn_pass2_unresolved_ops,
    reset_logical_txn_recovery_discarded_frames,
    reset_logical_txn_torn_frames,
    reset_oldest_required_ts_lag_ms,
    reset_overflow_pages_freed,
    reset_overflow_pages_in_use,
    reset_overflow_refcount_cas_retries,
    reset_parsed_logical_frames_len,
    reset_published_catalog_rebuild_count,
    reset_published_snapshot_rebuilds,
    reset_read_epoch_publish_count,
    reset_read_views_force_expired,
    reset_reconcile_duration_ms_p99,
    reset_reconcile_entries_dropped,
    reset_recovery_chain_commit_frames,
    reset_recovery_legacy_page_frames,
    reset_root_neutral_commit_count,
    reset_secondary_index_tombstone_hits,
    reset_version_chain_depth_p99,
    root_neutral_commit_count_snapshot,
    secondary_index_tombstone_hits_snapshot,
    set_active_read_views,
    set_deferred_free_queue_depth,
    set_delta_bearing_frames_ratio,
    set_history_store_bytes,
    set_oldest_required_ts_lag_ms,
    set_overflow_pages_in_use,
    set_parsed_logical_frames_len,
    set_reconcile_duration_ms_p99,
    set_version_chain_depth_p99,
    version_chain_depth_p99_snapshot,
};
#[allow(unused_imports)]
pub use read_view::{ChainSnapshot, ReadView, ReadViewRegistry};
#[allow(unused_imports)]
pub use timestamp::{HlcState, TimestampOracle, Ts};
#[allow(unused_imports)]
pub(crate) use transaction::{PrimaryOp, PrimaryWrite, SecIndexOp, SecIndexWrite, WriteTxn};
#[allow(unused_imports)]
pub use version::{OverflowRef, VersionData, VersionEntry, VersionState};
