#!/usr/bin/env bash
# cck-loop-phase4.sh - run Claude/Codex critic loops until both approve.
#
# Each loop iteration starts fresh reviewer sessions, saves both reviews, and
# exits those sessions. If either reviewer rejects, a separate fresh Codex
# patcher session synthesizes the reviews and updates the Phase 04 docs/PRD.
# The script then starts a new iteration.
#
# Usage:
#   scripts/cck-loop-phase4.sh
#   scripts/cck-loop-phase4.sh --max 3
#   scripts/cck-loop-phase4.sh --dry-run
#
# Env overrides:
#   PROMPT_FILE          canonical CCK prompt file
#   ARTIFACT_DIR         per-round artifact directory
#   MAX_ITER             max loop iterations (default: 8)
#   REVIEW_TIMEOUT_SECS  per-reviewer timeout (default: 1200)
#   PATCH_TIMEOUT_SECS   patcher timeout (default: 1800)
#   CLAUDE_BIN           Claude CLI binary (default: claude)
#   CODEX_BIN            Codex CLI binary (default: codex)

set -euo pipefail

PROMPT_FILE="${PROMPT_FILE:-.omx/artifacts/cck-phase4-design-prd-vs-phase3-20260427-prompt.md}"
ARTIFACT_DIR="${ARTIFACT_DIR:-.omx/artifacts/cck-loop-phase4}"
MAX_ITER="${MAX_ITER:-8}"
REVIEW_TIMEOUT_SECS="${REVIEW_TIMEOUT_SECS:-1800}"
PATCH_TIMEOUT_SECS="${PATCH_TIMEOUT_SECS:-1800}"
CLAUDE_BIN="${CLAUDE_BIN:-claude}"
CODEX_BIN="${CODEX_BIN:-codex}"
DRY_RUN=0
ACTIVE_PIDS=()
CURRENT_TIMEOUT_PID=""

TARGET_FILES=(
  "docs/STORAGE-UPGRADE-PHASE-04-RECONCILIATION-AND-CHECKPOINT.md"
  ".omc/phase-04-prd.json"
  ".omx/plans/prd-phase-04-reconciliation-checkpoint.md"
  ".omx/plans/test-spec-phase-04-reconciliation-checkpoint.md"
)

usage() {
  sed -n '1,20p' "$0"
}

die() {
  echo "error: $*" >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      ;;
    --max)
      shift
      [ $# -gt 0 ] || die "--max requires an integer"
      MAX_ITER="$1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown arg: $1"
      ;;
  esac
  shift
done

case "$MAX_ITER" in
  ''|*[!0-9]*)
    die "MAX_ITER must be an integer"
    ;;
esac
case "$REVIEW_TIMEOUT_SECS" in
  ''|*[!0-9]*)
    die "REVIEW_TIMEOUT_SECS must be an integer"
    ;;
esac
case "$PATCH_TIMEOUT_SECS" in
  ''|*[!0-9]*)
    die "PATCH_TIMEOUT_SECS must be an integer"
    ;;
esac

ROOT="$(pwd)"
[ -f "$PROMPT_FILE" ] || die "prompt file not found: $PROMPT_FILE"
for target in "${TARGET_FILES[@]}"; do
  [ -f "$target" ] || die "target file not found: $target"
done

command -v jq >/dev/null || die "jq is required"
command -v rg >/dev/null || die "rg is required"
command -v shasum >/dev/null || die "shasum is required"
command -v pgrep >/dev/null || die "pgrep is required"
command -v "$CODEX_BIN" >/dev/null || die "$CODEX_BIN not found"
command -v "$CLAUDE_BIN" >/dev/null || die "$CLAUDE_BIN not found"

mkdir -p "$ARTIFACT_DIR"

terminate_tree() {
  local pid="$1"
  local child

  for child in $(pgrep -P "$pid" 2>/dev/null || true); do
    terminate_tree "$child"
  done

  kill -TERM "$pid" 2>/dev/null || true
}

cleanup_active() {
  local pid

  if [ -n "${CURRENT_TIMEOUT_PID:-}" ]; then
    terminate_tree "$CURRENT_TIMEOUT_PID"
  fi

  for pid in "${ACTIVE_PIDS[@]:-}"; do
    terminate_tree "$pid"
  done
}

trap 'cleanup_active; exit 130' INT TERM

run_with_timeout() {
  local seconds="$1"
  shift

  "$@" <&0 &
  local pid=$!
  CURRENT_TIMEOUT_PID="$pid"

  (
    sleep "$seconds"
    if kill -0 "$pid" 2>/dev/null; then
      echo "[cck-loop] timeout after ${seconds}s: $*" >&2
      terminate_tree "$pid"
      sleep 5
      if kill -0 "$pid" 2>/dev/null; then
        kill -KILL "$pid" 2>/dev/null || true
      fi
    fi
  ) &
  local watchdog=$!

  set +e
  wait "$pid"
  local rc=$?
  set -e

  kill "$watchdog" 2>/dev/null || true
  wait "$watchdog" 2>/dev/null || true
  if [ "${CURRENT_TIMEOUT_PID:-}" = "$pid" ]; then
    CURRENT_TIMEOUT_PID=""
  fi
  return "$rc"
}

hash_targets() {
  shasum "$PROMPT_FILE" "${TARGET_FILES[@]}" | shasum | awk '{print $1}'
}

make_convergence_snapshot() {
  local output="$1"

  {
    printf '# Phase 04 Convergence Snapshot\n\n'
    printf 'Generated by `scripts/cck-loop-phase4.sh` before reviewer prompts.\n\n'

    printf '## Artifact Sizes\n\n'
    wc -l "${TARGET_FILES[@]}"
    printf '\n'

    printf '## Canonical PRD Story Map\n\n'
    jq -r '
      .stories[]
      | "- \(.id): \(.title // "(untitled)")"
        + " | priority=\(.priority // "n/a")"
        + " | depends_on=\((.dependencies // []) | if length == 0 then "none" else join(",") end)"
    ' .omc/phase-04-prd.json
    printf '\n'

    printf '## Canonical Approval Definition\n\n'
    jq -r '.meta.approval_definition // "(missing)"' .omc/phase-04-prd.json
    printf '\n'

    printf '## Known Stale-Text Scan\n\n'
    if rg -n \
      'durable logical frame with no matching ChainCommit|same two-condition drain rule|kind does not affect normal drain|PageLifetimeKind` does not affect normal eligibility|reserved_bytes_101_to_127_are_zero' \
      "${TARGET_FILES[@]}"; then
      true
    else
      printf 'No known stale-text matches.\n'
    fi
    printf '\n'

    printf '## High-Drift Marker Scan\n\n'
    if rg -n \
      'inline reconcile|inline threshold|BoundaryScan|append_checkpoint_commit_boundary|JOURNAL_FORMAT_VERSION|RETIRED_PRE_RELEASE_JOURNAL_FORMAT_VERSIONS|index_owner_by_id|PoolPressureState|pool_pressure_threshold|pool_only_flush|last_checkpoint_ts|PageLifetimeQueue' \
      "${TARGET_FILES[@]}"; then
      true
    else
      printf 'No high-drift marker matches.\n'
    fi
  } >"$output"
}

make_review_prompt() {
  local output="$1"
  local snapshot="$2"

  {
    cat "$PROMPT_FILE"
    printf '\n\n'
    printf 'Per-round convergence snapshot:\n'
    printf -- '- `%s`\n\n' "$snapshot"
    cat <<'PROMPT'
Convergence review contract:
- Treat `.omc/phase-04-prd.json` as the single canonical execution spec.
  The phase design doc, Markdown PRD wrapper, and test-spec wrapper must
  converge to it. They may summarize, explain rationale, or point to it, but
  they must not define conflicting implementation rules.
- Start by checking cross-artifact convergence in this order:
  1. Canonical PRD self-consistency.
  2. Phase design doc drift from the canonical PRD.
  3. Markdown PRD wrapper drift from the canonical PRD.
  4. Test-spec wrapper drift from the canonical PRD.
  5. Current source/API ownership gaps that make the canonical PRD unbuildable.
- Prefer convergence by deletion or narrowing over adding more parallel prose.
  If a wrapper or design section duplicates a canonical PRD rule incorrectly,
  flag the duplicated section as the edit target instead of expanding every
  artifact with more detail.
- Do not require full implementation-detail expansion when the canonical PRD
  already names the owning story, invariant, and test. Flag only details that
  are necessary for a senior engineer to implement without choosing between
  contradictory behaviors.
- Severity discipline:
  BLOCKER = data loss/corruption, crash/recovery unsoundness, canonical PRD
  contradiction, or a required primitive with no owning story.
  MAJOR = implementation-critical ambiguity, wrapper/test drift likely to drive
  wrong code, or missing test coverage for a named failure mode.
  MINOR/NIT = polish, wording, count drift, or optional hardening; these do not
  block approval by themselves.
- For every BLOCKER or MAJOR, include exactly one `Convergence target:` line
  choosing one of:
  canonical-prd, phase-doc, markdown-wrapper, test-spec, source-ownership,
  defer-out-of-phase, or reject-finding.
- Do not reopen settled areas unless you have new evidence from current files.
  Prior review history is context, not a source of truth.

Scale-control contract:
- Read the convergence snapshot first. Use it as a map for artifact size,
  canonical story ownership, approval definition, known stale phrases, and
  high-drift markers.
- Do not attempt to exhaustively restate or re-review every paragraph. Review
  by convergence risk: canonical PRD self-consistency, wrapper/doc drift, then
  source/API ownership gaps.
- Report every data-loss, corruption, crash/recovery, or security BLOCKER you
  find. For other BLOCKER/MAJOR findings, report only the highest-signal set
  needed to make the next patch converge; group repeated drift under one
  finding instead of filing line-by-line duplicates.
- If the same issue appears in several artifacts, file one finding with one
  convergence target and list the affected artifacts.

Review output contract:
- This is a read-only critic run. Do not edit files.
- Include a short `Convergence summary` before findings:
  canonical-prd: aligned|drift|blocked
  phase-doc: aligned|drift|blocked
  markdown-wrapper: aligned|drift|blocked
  test-spec: aligned|drift|blocked
- End with exactly one final line:
  VERDICT: APPROVE
  or
  VERDICT: REJECT
- Use APPROVE only when there are no BLOCKER or MAJOR findings requiring
  design-doc, PRD, wrapper, or test-spec changes.
PROMPT
  } >"$output"
}

run_claude_review() {
  local round_dir="$1"
  local prompt_file="$2"
  local output="$round_dir/claude-review.md"
  local log="$round_dir/claude-review.log"

  run_with_timeout "$REVIEW_TIMEOUT_SECS" \
    "$CLAUDE_BIN" -p \
    --permission-mode bypassPermissions \
    --add-dir "$ROOT" \
    --allowedTools Read,Grep,Glob \
    <"$prompt_file" >"$output" 2>"$log"
}

run_codex_review() {
  local round_dir="$1"
  local prompt_file="$2"
  local output="$round_dir/codex-review.md"
  local log="$round_dir/codex-review.log"

  run_with_timeout "$REVIEW_TIMEOUT_SECS" \
    "$CODEX_BIN" exec \
    -C "$ROOT" \
    --sandbox read-only \
    -c 'approval_policy="never"' \
    --ephemeral \
    --output-last-message "$output" \
    - <"$prompt_file" >"$log" 2>&1
}

is_approved() {
  local file="$1"

  grep -Eiq '^VERDICT:[[:space:]]*APPROVE[[:space:]]*$' "$file"
}

is_patched() {
  local file="$1"

  grep -Eiq '^PATCHER_STATUS:[[:space:]]*PATCHED[[:space:]]*$' "$file"
}

make_patch_prompt() {
  local output="$1"
  local round_dir="$2"

  {
    cat <<'PROMPT'
You are a fresh Codex patcher in an automated CCK loop for Phase 04.

Goal:
- Read the canonical critic prompt and both reviewer reports.
- Synthesize the BLOCKER/MAJOR findings into convergence decisions.
- Make the minimum necessary edits so the Phase 04 artifacts converge around
  one canonical execution spec instead of growing parallel, drifting prose.
- Use .omc/phase-04-prd.json as the canonical execution spec.
- Patch the canonical PRD first when the canonical rule is wrong or incomplete.
  Then narrow, delete, or mirror the phase doc / wrappers only as needed.
- Prefer deleting duplicated wrapper/design detail over copying more detail
  into every artifact.
- Use WiredTiger as the reference implementation direction when the reviewers
  identify ambiguity.
- Do not edit source code. If a finding identifies missing source ownership,
  patch the PRD so an owning story creates the future primitive/test before any
  consumer story uses it.

PROMPT
    printf 'Inputs:\n'
    printf -- '- Canonical prompt: %s\n' "$PROMPT_FILE"
    printf -- '- Convergence snapshot: %s/convergence-snapshot.md\n' "$round_dir"
    printf -- '- Claude review: %s/claude-review.md\n' "$round_dir"
    printf -- '- Codex review: %s/codex-review.md\n' "$round_dir"
    cat <<'PROMPT'

Primary editable artifacts:
- docs/STORAGE-UPGRADE-PHASE-04-RECONCILIATION-AND-CHECKPOINT.md
- .omc/phase-04-prd.json
- .omx/plans/prd-phase-04-reconciliation-checkpoint.md
- .omx/plans/test-spec-phase-04-reconciliation-checkpoint.md

Convergence rules:
0. Read the convergence snapshot first. Use it to avoid broad, repeated scans
   of the full Phase 04 spec when the reviewer findings already name a
   convergence target.
1. Treat every BLOCKER or MAJOR as requiring an explicit disposition:
   patched, deferred-out-of-phase, rejected-finding, or blocked.
2. Do not automatically expand scope because a reviewer suggested a possible
   primitive. First choose the smallest convergence target:
   canonical-prd, phase-doc, markdown-wrapper, test-spec, source-ownership,
   defer-out-of-phase, or reject-finding.
3. If the canonical PRD is already clear and a wrapper/design doc conflicts
   with it, edit the wrapper/design doc to remove or summarize the duplicate
   detail. Do not rewrite the canonical PRD unless it is actually wrong.
4. If the canonical PRD and design doc both contain the same rule, keep the
   acceptance-test wording in the PRD and reduce design-doc wording to intent,
   rationale, or a pointer unless exact prose is needed for implementation.
5. Keep all four artifacts aligned after edits. Alignment means the wrappers
   cannot require behavior that the canonical PRD does not own.
6. Preserve the WiredTiger compatibility review dimension in the canonical
   prompt. If reviewers flag a WiredTiger mismatch, patch toward the smallest
   conservative WiredTiger-compatible behavior that mqlite can actually build.
7. Do not patch MINOR/NIT findings unless they touch the same lines needed for
   BLOCKER/MAJOR convergence or they are pure deletion of stale/conflicting
   text.
8. Your final response must include a compact convergence ledger with one row
   per BLOCKER/MAJOR finding: reviewer, severity, short issue, disposition,
   convergence target, files changed.

Required validation:
- Run `jq empty .omc/phase-04-prd.json`.
- Run:
  `rg -n 'durable logical frame with no matching ChainCommit|same two-condition drain rule|kind does not affect normal drain|PageLifetimeKind` does not affect normal eligibility|reserved_bytes_101_to_127_are_zero' docs/STORAGE-UPGRADE-PHASE-04-RECONCILIATION-AND-CHECKPOINT.md .omc/phase-04-prd.json .omx/plans/prd-phase-04-reconciliation-checkpoint.md .omx/plans/test-spec-phase-04-reconciliation-checkpoint.md`
  This rg command should return no matches unless you explain why a remaining
  match is intentional.
- Run at least one additional targeted `rg` check for every stale phrase or
  symbol you remove as part of convergence.
- End your final response with exactly one final line:
  PATCHER_STATUS: PATCHED
  or
  PATCHER_STATUS: BLOCKED
PROMPT
  } >"$output"
}

run_patcher() {
  local round_dir="$1"
  local prompt_file="$round_dir/patcher-prompt.md"
  local output="$round_dir/patcher.md"
  local log="$round_dir/patcher.log"

  make_patch_prompt "$prompt_file" "$round_dir"
  run_with_timeout "$PATCH_TIMEOUT_SECS" \
    "$CODEX_BIN" exec \
    -C "$ROOT" \
    --dangerously-bypass-approvals-and-sandbox \
    --ephemeral \
    --output-last-message "$output" \
    - <"$prompt_file" >"$log" 2>&1
}

validate_artifacts() {
  jq empty .omc/phase-04-prd.json
  rg -n \
    'durable logical frame with no matching ChainCommit|same two-condition drain rule|kind does not affect normal drain|PageLifetimeKind` does not affect normal eligibility|reserved_bytes_101_to_127_are_zero' \
    docs/STORAGE-UPGRADE-PHASE-04-RECONCILIATION-AND-CHECKPOINT.md \
    .omc/phase-04-prd.json \
    .omx/plans/prd-phase-04-reconciliation-checkpoint.md \
    .omx/plans/test-spec-phase-04-reconciliation-checkpoint.md >/dev/null && {
      echo "error: stale text scan matched; inspect artifacts" >&2
      return 1
    }
  return 0
}

if [ "$DRY_RUN" = 1 ]; then
  echo "[cck-loop] dry run"
  echo "[cck-loop] root: $ROOT"
  echo "[cck-loop] prompt: $PROMPT_FILE"
  echo "[cck-loop] artifact dir: $ARTIFACT_DIR"
  echo "[cck-loop] max iterations: $MAX_ITER"
  exit 0
fi

iter=0
while :; do
  iter=$((iter + 1))
  if [ "$iter" -gt "$MAX_ITER" ]; then
    echo "[cck-loop] stopped after $MAX_ITER iterations without dual approval"
    exit 3
  fi

  round_id="$(date +%Y%m%d-%H%M%S)-round-${iter}"
  round_dir="$ARTIFACT_DIR/$round_id"
  mkdir -p "$round_dir"

  convergence_snapshot="$round_dir/convergence-snapshot.md"
  make_convergence_snapshot "$convergence_snapshot"

  review_prompt="$round_dir/reviewer-prompt.md"
  make_review_prompt "$review_prompt" "$convergence_snapshot"

  echo "[cck-loop] round $iter: launching Claude and Codex critics"
  before_hash="$(hash_targets)"

  run_claude_review "$round_dir" "$review_prompt" &
  claude_pid=$!
  run_codex_review "$round_dir" "$review_prompt" &
  codex_pid=$!
  ACTIVE_PIDS=("$claude_pid" "$codex_pid")

  set +e
  wait "$claude_pid"
  claude_rc=$?
  wait "$codex_pid"
  codex_rc=$?
  set -e
  ACTIVE_PIDS=()

  if [ "$claude_rc" -ne 0 ] || [ "$codex_rc" -ne 0 ]; then
    echo "[cck-loop] critic failure in $round_dir"
    echo "[cck-loop] claude rc=$claude_rc codex rc=$codex_rc"
    exit 4
  fi

  claude_status="REJECT"
  codex_status="REJECT"
  if is_approved "$round_dir/claude-review.md"; then
    claude_status="APPROVE"
  fi
  if is_approved "$round_dir/codex-review.md"; then
    codex_status="APPROVE"
  fi

  echo "[cck-loop] round $iter verdicts: claude=$claude_status codex=$codex_status"
  if [ "$claude_status" = "APPROVE" ] && [ "$codex_status" = "APPROVE" ]; then
    validate_artifacts
    echo "[cck-loop] both reviewers approved"
    echo "[cck-loop] artifacts: $round_dir"
    exit 0
  fi

  if [ "$iter" -ge "$MAX_ITER" ]; then
    echo "[cck-loop] stopped after $MAX_ITER iterations without dual approval"
    echo "[cck-loop] final rejected-review artifacts: $round_dir"
    exit 3
  fi

  echo "[cck-loop] round $iter: launching patcher"
  set +e
  run_patcher "$round_dir"
  patcher_rc=$?
  set -e
  if [ "$patcher_rc" -ne 0 ]; then
    echo "[cck-loop] patcher failed in $round_dir"
    echo "[cck-loop] patcher rc=$patcher_rc"
    exit 6
  fi
  if ! is_patched "$round_dir/patcher.md"; then
    echo "[cck-loop] patcher did not report PATCHER_STATUS: PATCHED"
    echo "[cck-loop] inspect $round_dir/patcher.md"
    exit 6
  fi
  validate_artifacts

  after_hash="$(hash_targets)"
  if [ "$before_hash" = "$after_hash" ]; then
    echo "[cck-loop] patcher made no target changes after rejection"
    echo "[cck-loop] inspect $round_dir/patcher.md"
    exit 5
  fi

  echo "[cck-loop] round $iter patched; starting a fresh review loop"
done
