//! MongoDB-compatible ObjectId generation.
//!
//! Produces 12-byte ObjectIds matching the MongoDB specification:
//!
//! ```text
//! [timestamp(4)] [random(5)] [counter(3)]
//! ```
//!
//! | Field | Size | Description |
//! |-------|------|-------------|
//! | timestamp | 4 bytes | Seconds since Unix epoch, big-endian |
//! | random | 5 bytes | Per-process random value, initialized once |
//! | counter | 3 bytes | Low 3 bytes of an `AtomicU32`, big-endian |
//!
//! ## Thread safety
//!
//! [`ObjectIdGenerator::generate`] is safe to call from multiple threads
//! concurrently. The 3-byte counter uses a global [`AtomicU32`] with
//! [`Ordering::Relaxed`] — sufficient for uniqueness within a process (we
//! only need a monotonically advancing value, not ordering guarantees across
//! threads).
//!
//! The 5-byte random component is initialized once per process using a
//! [`OnceLock`]. The initialization mixes system time nanoseconds, the
//! process ID, and a stack address (which varies per process due to ASLR) to
//! produce a process-unique value. Not cryptographically secure, but
//! sufficient for ObjectId uniqueness.
//!
//! ## Relationship to `bson::oid::ObjectId`
//!
//! The public API re-exports [`bson::oid::ObjectId`] as the canonical ObjectId
//! type. [`ObjectIdGenerator::generate`] constructs values using
//! [`bson::oid::ObjectId::from_parts`], so the result is directly usable as a
//! BSON ObjectId without any conversion.

use std::sync::{
    atomic::{AtomicU32, Ordering},
    OnceLock,
};
use std::time::{SystemTime, UNIX_EPOCH};

use bson::oid::ObjectId;

// ---------------------------------------------------------------------------
// Process-static state
// ---------------------------------------------------------------------------

/// Per-process 5-byte random component, initialized once on first use.
static PROCESS_RANDOM: OnceLock<[u8; 5]> = OnceLock::new();

/// Monotonically incrementing counter. Only the low 24 bits are used (the
/// MongoDB ObjectId counter field is 3 bytes = 24 bits).
static COUNTER: AtomicU32 = AtomicU32::new(0);

// ---------------------------------------------------------------------------
// ObjectIdGenerator
// ---------------------------------------------------------------------------

/// MongoDB-compatible ObjectId generator.
///
/// All methods are static; there is no per-instance state — the generator uses
/// global statics ([`PROCESS_RANDOM`] and [`COUNTER`]).
pub(crate) struct ObjectIdGenerator;

impl ObjectIdGenerator {
    /// Generate a new [`ObjectId`] matching the MongoDB 12-byte format.
    ///
    /// ## Format
    ///
    /// ```text
    /// bytes[0..4]  = seconds since Unix epoch (u32 big-endian)
    /// bytes[4..9]  = 5-byte per-process random value
    /// bytes[9..12] = 3-byte counter (low bytes of AtomicU32, big-endian)
    /// ```
    ///
    /// ## Thread Safety
    ///
    /// Safe to call concurrently from any number of threads.
    pub(crate) fn generate() -> ObjectId {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs() as u32;
        let process_id = *PROCESS_RANDOM.get_or_init(init_process_random);
        let [_, b1, b2, b3] = COUNTER.fetch_add(1, Ordering::Relaxed).to_be_bytes();
        let counter = [b1, b2, b3];

        ObjectId::from_parts(timestamp, process_id, counter)
    }
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/// Initialize the 5-byte per-process random component.
///
/// Uses a combination of:
/// - Current time nanoseconds (changes between processes/restarts)
/// - Process ID (unique per OS process)
/// - Stack address (varies per process due to ASLR)
///
/// Not cryptographically secure. Suitable for ensuring that ObjectIds
/// generated by different processes are very unlikely to collide.
fn init_process_random() -> [u8; 5] {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut h = DefaultHasher::new();

    // Mix in high-resolution time
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos()
        .hash(&mut h);

    // Mix in process ID
    std::process::id().hash(&mut h);

    // Mix in a stack address for ASLR-based entropy
    let stack_probe: usize = &h as *const _ as usize;
    stack_probe.hash(&mut h);

    let v1 = h.finish();

    // Second round to fill all 5 bytes
    v1.hash(&mut h);
    let v2 = h.finish();

    let b1 = v1.to_le_bytes();
    let b2 = v2.to_le_bytes();

    [b1[0], b1[1], b1[2], b1[3], b2[0]]
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[path = "tests/oid.rs"]
mod tests;
